"""
Bug Triage & Patch Validation - Bug Dataset
24 realistic bug reports across 3 tasks. Each bug has a multi-step
workflow: reproduce -> diagnose -> patch -> validate -> close.
"""
from __future__ import annotations
from typing import Any, Dict, List

# ---------------------------------------------------------------------------
# Task 1 - EASY: Severity classification + routing (8 bugs)
# Agent must correctly assess severity and component.
# State machine: just needs DIAGNOSE + CLOSE actions.
# ---------------------------------------------------------------------------

TASK1_BUGS: List[Dict[str, Any]] = [
    {
        "bug_id": "BUG-101",
        "title": "Login button does nothing on Safari 17",
        "description": "Users on Safari 17.x cannot log in. Button click has no effect. Console shows: TypeError: Cannot read property 'submit' of null",
        "stack_trace": "TypeError: Cannot read property 'submit' of null\n  at LoginForm.handleSubmit (login.js:42)\n  at HTMLElement.onclick",
        "steps_to_reproduce": "1. Open Safari 17\n2. Go to /login\n3. Enter credentials\n4. Click Login",
        "reported_by": "customer_support@bigclient.com",
        "reporter_type": "customer",
        "created_at": "2024-01-15T09:00:00",
        "affected_version": "2.4.1",
        "environment": "production",
        "num_affected_users": 1240,
        "has_workaround": True,
        "true_severity": "high",
        "true_component": "frontend",
        "needs_reproduce": True,
        "reproduce_keywords": ["safari", "login", "submit", "null", "test"],
        "root_cause": "form.submit reference is null in Safari 17 due to shadow DOM change",
        "diagnosis_keywords": ["safari", "dom", "form", "null", "shadow", "browser"],
        "patch_keywords": ["querySelector", "getElementById", "form", "submit", "null check"],
        "patch_valid_if": ["null", "check", "safari", "form"],
    },
    {
        "bug_id": "BUG-102",
        "title": "Button color slightly off on dark mode",
        "description": "The 'Save' button in dark mode shows #1a1a2e instead of #1a1a2f. Barely noticeable.",
        "stack_trace": None,
        "steps_to_reproduce": "1. Enable dark mode\n2. Look at Save button",
        "reported_by": "intern@company.com",
        "reporter_type": "internal",
        "created_at": "2024-01-15T10:00:00",
        "affected_version": "2.4.1",
        "environment": "staging",
        "num_affected_users": 0,
        "has_workaround": True,
        "true_severity": "low",
        "true_component": "frontend",
        "needs_reproduce": False,
        "reproduce_keywords": [],
        "root_cause": "CSS variable off by one hex digit",
        "diagnosis_keywords": ["css", "color", "variable", "dark", "hex"],
        "patch_keywords": ["css", "color", "variable", "theme"],
        "patch_valid_if": ["css", "color"],
    },
    {
        "bug_id": "BUG-103",
        "title": "CRITICAL: Payment processing returns 500 on all Visa cards",
        "description": "Since deploy v2.4.1 at 14:00 UTC, ALL Visa card payments fail with 500. Revenue impact: ~$50k/hour. Stripe dashboard shows no errors on their end.",
        "stack_trace": "stripe.error.InvalidRequestError: No such customer: 'cus_None'\n  at payments/process.py:88 in charge_customer\n  at payments/views.py:134 in process_payment",
        "steps_to_reproduce": "1. Add any item to cart\n2. Enter Visa card details\n3. Submit payment\n4. Observe 500 error",
        "reported_by": "oncall@company.com",
        "reporter_type": "internal",
        "created_at": "2024-01-15T14:15:00",
        "affected_version": "2.4.1",
        "environment": "production",
        "num_affected_users": 8500,
        "has_workaround": False,
        "true_severity": "critical",
        "true_component": "payments",
        "needs_reproduce": True,
        "reproduce_keywords": ["visa", "payment", "stripe", "500", "customer", "test"],
        "root_cause": "customer_id is None due to missing migration - new users don't have Stripe customer ID created on signup",
        "diagnosis_keywords": ["customer_id", "none", "migration", "stripe", "signup", "null"],
        "patch_keywords": ["customer_id", "create", "stripe", "migration", "get_or_create", "none check"],
        "patch_valid_if": ["customer", "none", "create", "stripe"],
    },
    {
        "bug_id": "BUG-104",
        "title": "SQL injection possible in search endpoint",
        "description": "Security researcher reports: GET /api/search?q='; DROP TABLE users;-- returns 500 instead of sanitised error. Raw query construction confirmed in search.py:67.",
        "stack_trace": "psycopg2.errors.SyntaxError: syntax error at or near \"DROP\"\n  at api/search.py:67 in execute_search",
        "steps_to_reproduce": "curl '/api/search?q=%27%3B+DROP+TABLE+users%3B--'",
        "reported_by": "security@bugbounty.io",
        "reporter_type": "security_researcher",
        "created_at": "2024-01-15T11:00:00",
        "affected_version": "2.4.0",
        "environment": "production",
        "num_affected_users": 0,
        "has_workaround": False,
        "true_severity": "critical",
        "true_component": "security",
        "needs_reproduce": True,
        "reproduce_keywords": ["sql", "injection", "query", "sanitize", "parameterize", "test"],
        "root_cause": "f-string SQL construction without parameterisation in search.py:67",
        "diagnosis_keywords": ["sql", "injection", "f-string", "parameteriz", "raw", "query", "format"],
        "patch_keywords": ["parameteriz", "prepared", "statement", "cursor.execute", "placeholder", "%s"],
        "patch_valid_if": ["parameteriz", "prepared", "%s", "placeholder"],
        "requires_escalation": True,
    },
    {
        "bug_id": "BUG-105",
        "title": "Export to CSV truncates at 10,000 rows",
        "description": "Large dataset exports silently truncate at exactly 10,000 rows. No error shown. Affects enterprise customers with large datasets.",
        "stack_trace": None,
        "steps_to_reproduce": "1. Create dataset with 15,000 rows\n2. Click Export CSV\n3. Check row count in downloaded file",
        "reported_by": "enterprise@client.com",
        "reporter_type": "customer",
        "created_at": "2024-01-15T13:00:00",
        "affected_version": "2.3.0",
        "environment": "production",
        "num_affected_users": 340,
        "has_workaround": False,
        "true_severity": "high",
        "true_component": "api",
        "needs_reproduce": True,
        "reproduce_keywords": ["csv", "export", "10000", "limit", "paginate", "test"],
        "root_cause": "Hardcoded LIMIT 10000 in export query, no pagination implemented",
        "diagnosis_keywords": ["limit", "10000", "hardcode", "paginate", "query", "export"],
        "patch_keywords": ["paginate", "chunk", "stream", "limit", "remove", "batch"],
        "patch_valid_if": ["paginate", "chunk", "stream", "batch"],
    },
    {
        "bug_id": "BUG-106",
        "title": "Typo in error message: 'Authentification' should be 'Authentication'",
        "description": "Error message on login page says 'Authentification failed'. Minor typo.",
        "stack_trace": None,
        "steps_to_reproduce": "1. Enter wrong password\n2. See error message",
        "reported_by": "qa@company.com",
        "reporter_type": "internal",
        "created_at": "2024-01-15T15:00:00",
        "affected_version": "2.4.0",
        "environment": "staging",
        "num_affected_users": 0,
        "has_workaround": True,
        "true_severity": "low",
        "true_component": "frontend",
        "needs_reproduce": False,
        "reproduce_keywords": [],
        "root_cause": "Typo in i18n string",
        "diagnosis_keywords": ["typo", "string", "i18n", "translation", "message"],
        "patch_keywords": ["authentication", "string", "typo", "fix", "message"],
        "patch_valid_if": ["authentication", "string"],
    },
    {
        "bug_id": "BUG-107",
        "title": "Database connection pool exhausted under load",
        "description": "Under load testing (500 concurrent users), DB connections exhaust after ~2 min. Pool size 20, no connection releasing observed. ORM sessions not closed properly.",
        "stack_trace": "sqlalchemy.exc.TimeoutError: QueuePool limit of size 20 overflow 10 reached, connection timed out\n  at api/middleware.py:34",
        "steps_to_reproduce": "1. Run load test: locust -u 500 -r 50\n2. Observe after 2 minutes",
        "reported_by": "devops@company.com",
        "reporter_type": "internal",
        "created_at": "2024-01-15T16:00:00",
        "affected_version": "2.4.1",
        "environment": "staging",
        "num_affected_users": 0,
        "has_workaround": False,
        "true_severity": "high",
        "true_component": "database",
        "needs_reproduce": True,
        "reproduce_keywords": ["pool", "connection", "load", "session", "close", "test"],
        "root_cause": "SQLAlchemy sessions not closed in finally block in middleware - connection leak on exceptions",
        "diagnosis_keywords": ["session", "close", "leak", "finally", "context", "manager", "pool"],
        "patch_keywords": ["finally", "close", "context manager", "with", "session", "try"],
        "patch_valid_if": ["finally", "close", "with", "context"],
    },
    {
        "bug_id": "BUG-108",
        "title": "User avatar not loading for accounts created before 2023",
        "description": "Legacy accounts (pre-2023) show broken image for avatar. New accounts fine. Profile page shows 404 for avatar URL /avatars/legacy/<id>.jpg",
        "stack_trace": None,
        "steps_to_reproduce": "1. Log in with pre-2023 account\n2. Go to profile page\n3. Observe broken avatar",
        "reported_by": "customer@old-account.com",
        "reporter_type": "customer",
        "created_at": "2024-01-15T17:00:00",
        "affected_version": "2.4.0",
        "environment": "production",
        "num_affected_users": 12000,
        "has_workaround": False,
        "true_severity": "medium",
        "true_component": "frontend",
        "needs_reproduce": False,
        "reproduce_keywords": [],
        "root_cause": "S3 bucket migration didn't copy legacy avatar path structure",
        "diagnosis_keywords": ["s3", "migration", "path", "legacy", "bucket", "404", "url"],
        "patch_keywords": ["s3", "migrate", "copy", "path", "legacy", "redirect", "url"],
        "patch_valid_if": ["s3", "migrate", "path", "redirect"],
    },
]

TASK1_CONFIG = {
    "task_id": "task1_easy_severity_routing",
    "description": "Assess severity and component for 8 bugs. Use DIAGNOSE to identify root cause, CLOSE to resolve.",
    "difficulty": "easy",
    "max_steps": 24,
    "bugs": TASK1_BUGS,
    "required_actions": ["diagnose", "close"],
    "scoring": {
        "severity_weight": 0.45,
        "component_weight": 0.30,
        "diagnosis_weight": 0.25,
    },
}

# ---------------------------------------------------------------------------
# Task 2 - MEDIUM: Full debug cycle (reproduce -> diagnose -> patch -> validate -> close)
# 5 bugs requiring multi-step workflows
# ---------------------------------------------------------------------------

TASK2_BUGS: List[Dict[str, Any]] = [
    {
        "bug_id": "BUG-201",
        "title": "Race condition in session token refresh causing logout",
        "description": "Users report being randomly logged out mid-session, roughly every 30-90 minutes. More frequent under high traffic. Seems to affect users with multiple tabs open.",
        "stack_trace": "jwt.exceptions.ExpiredSignatureError: Signature has expired\n  at auth/middleware.py:89 in verify_token\n  Concurrent refresh detected: token_id=abc123 already refreshed by thread-2",
        "steps_to_reproduce": "1. Open app in 3+ browser tabs\n2. Wait 30+ minutes\n3. Perform any action in one tab\n4. Observe logout in other tabs",
        "reported_by": "support@company.com",
        "reporter_type": "internal",
        "created_at": "2024-01-16T08:00:00",
        "affected_version": "2.4.1",
        "environment": "production",
        "num_affected_users": 3200,
        "has_workaround": False,
        "true_severity": "high",
        "true_component": "auth",
        "reproduce_keywords": ["race", "concurrent", "thread", "lock", "token", "refresh", "tab"],
        "root_cause": "No mutex/lock on token refresh - multiple concurrent requests all invalidate and reissue, first wins, rest get expired token",
        "diagnosis_keywords": ["race", "condition", "mutex", "lock", "concurrent", "thread", "atomic", "refresh"],
        "patch_keywords": ["lock", "mutex", "atomic", "redis", "distributed", "refresh", "once", "idempotent"],
        "patch_valid_if": ["lock", "mutex", "atomic", "redis"],
        "test_valid_if": ["concurrent", "test", "thread", "race", "pass", "assert"],
    },
    {
        "bug_id": "BUG-202",
        "title": "Memory leak in websocket handler - server OOM after 6 hours",
        "description": "Production server runs out of memory (~8GB) after approximately 6 hours. Heap dump shows millions of unclosed WebSocket listener references. Server requires daily restart.",
        "stack_trace": "MemoryError: Unable to allocate 256 MiB\n  at websocket/handler.py:156 in register_listener\nHeap analysis: 2.1M EventListener objects, 0 released",
        "steps_to_reproduce": "1. Run server\n2. Simulate 100 concurrent WS connections opening/closing over 2 hours\n3. Monitor heap size growth",
        "reported_by": "sre@company.com",
        "reporter_type": "internal",
        "created_at": "2024-01-16T09:00:00",
        "affected_version": "2.3.5",
        "environment": "production",
        "num_affected_users": 0,
        "has_workaround": True,
        "true_severity": "critical",
        "true_component": "infra",
        "reproduce_keywords": ["websocket", "memory", "leak", "listener", "close", "heap", "test"],
        "root_cause": "Event listeners registered on WebSocket open but never removed on close - closure captures reference preventing GC",
        "diagnosis_keywords": ["listener", "remove", "gc", "reference", "closure", "garbage", "collect", "leak"],
        "patch_keywords": ["removeEventListener", "cleanup", "finally", "close", "gc", "weak", "reference"],
        "patch_valid_if": ["remove", "cleanup", "finally", "close"],
        "test_valid_if": ["memory", "leak", "listener", "assert", "gc", "pass"],
    },
    {
        "bug_id": "BUG-203",
        "title": "Decimal precision loss in invoice totals - billing $0.01 short",
        "description": "Invoice totals are consistently $0.01 less than they should be for orders with tax. Customer noticed on $999.99 order: invoiced $999.98. Affects ~15% of orders.",
        "stack_trace": None,
        "steps_to_reproduce": "1. Create order with items totalling $909.08\n2. Apply 10% tax -> expected $1000.00 but got $999.99\n3. Check: 909.08 * 1.1 = 999.988 -> float truncation",
        "reported_by": "accounting@company.com",
        "reporter_type": "internal",
        "created_at": "2024-01-16T10:00:00",
        "affected_version": "2.4.0",
        "environment": "production",
        "num_affected_users": 4500,
        "has_workaround": False,
        "true_severity": "high",
        "true_component": "payments",
        "reproduce_keywords": ["decimal", "float", "precision", "tax", "rounding", "invoice", "test"],
        "root_cause": "Float arithmetic used for money calculations - IEEE 754 floating point rounding errors accumulate",
        "diagnosis_keywords": ["float", "decimal", "precision", "ieee", "rounding", "money", "arithmetic"],
        "patch_keywords": ["Decimal", "decimal", "quantize", "ROUND_HALF_UP", "money", "precision"],
        "patch_valid_if": ["decimal", "Decimal", "quantize", "round"],
        "test_valid_if": ["decimal", "assert", "equal", "precision", "tax", "pass"],
    },
    {
        "bug_id": "BUG-204",
        "title": "N+1 query on dashboard causing 30s page load",
        "description": "Dashboard page takes 25-35 seconds to load for accounts with >500 projects. Database shows 500+ sequential queries per page load. Was 2 seconds before v2.4.0.",
        "stack_trace": "Django Debug Toolbar: 647 queries in 28.4s\nRepeating pattern: SELECT * FROM projects WHERE id=? (x647)",
        "steps_to_reproduce": "1. Create account with 600 projects\n2. Load /dashboard\n3. Observe 30s load time and 600+ DB queries",
        "reported_by": "performance@company.com",
        "reporter_type": "internal",
        "created_at": "2024-01-16T11:00:00",
        "affected_version": "2.4.0",
        "environment": "production",
        "num_affected_users": 230,
        "has_workaround": False,
        "true_severity": "high",
        "true_component": "database",
        "reproduce_keywords": ["n+1", "query", "select_related", "prefetch", "dashboard", "test"],
        "root_cause": "ORM relationship access in template loop without prefetch_related - classic N+1",
        "diagnosis_keywords": ["n+1", "prefetch", "select_related", "eager", "lazy", "orm", "loop"],
        "patch_keywords": ["prefetch_related", "select_related", "eager", "join", "batch", "queryset"],
        "patch_valid_if": ["prefetch", "select_related", "eager", "join"],
        "test_valid_if": ["query", "count", "assert", "prefetch", "pass", "1 query"],
    },
    {
        "bug_id": "BUG-205",
        "title": "2FA bypass via concurrent login requests",
        "description": "Security researcher found: sending 2 identical POST /auth/verify-2fa requests simultaneously with same OTP - one succeeds even if the other should invalidate the token. OTP reuse possible within ~200ms window.",
        "stack_trace": "auth.log: OTP abc123 used at 14:00:00.100 by user@x.com\nauth.log: OTP abc123 used at 14:00:00.287 by user@x.com [SHOULD HAVE FAILED]",
        "steps_to_reproduce": "1. Start login, get OTP\n2. Send 2 concurrent POST /auth/verify-2fa with same OTP\n3. Both succeed",
        "reported_by": "bounty@security-research.com",
        "reporter_type": "security_researcher",
        "created_at": "2024-01-16T12:00:00",
        "affected_version": "2.4.1",
        "environment": "production",
        "num_affected_users": 0,
        "has_workaround": False,
        "true_severity": "critical",
        "true_component": "security",
        "reproduce_keywords": ["concurrent", "otp", "2fa", "race", "atomic", "redis", "test"],
        "root_cause": "OTP validity check and invalidation not atomic - check-then-act race condition",
        "diagnosis_keywords": ["atomic", "race", "check", "invalidate", "otp", "concurrent", "redis", "lock"],
        "patch_keywords": ["atomic", "redis", "setnx", "lock", "invalidate", "transaction", "otp"],
        "patch_valid_if": ["atomic", "redis", "setnx", "lock", "transaction"],
        "test_valid_if": ["concurrent", "otp", "assert", "fail", "second", "atomic", "pass"],
        "requires_escalation": True,
    },
]

TASK2_CONFIG = {
    "task_id": "task2_medium_full_debug_cycle",
    "description": "Full debug cycle for 5 bugs: REPRODUCE -> DIAGNOSE -> PATCH -> VALIDATE -> CLOSE. Quality of each step is graded.",
    "difficulty": "medium",
    "max_steps": 35,
    "bugs": TASK2_BUGS,
    "required_actions": ["reproduce", "diagnose", "patch", "validate", "close"],
    "scoring": {
        "severity_weight": 0.15,
        "component_weight": 0.10,
        "reproduce_weight": 0.15,
        "diagnosis_weight": 0.25,
        "patch_weight": 0.25,
        "validation_weight": 0.10,
    },
}

# ---------------------------------------------------------------------------
# Task 3 - HARD: Mixed backlog with trick bugs, duplicates, and time pressure
# 7 bugs. Some are duplicates of each other. One "bug" is actually by design.
# One requires security escalation. Agent must recognise patterns across bugs.
# ---------------------------------------------------------------------------

TASK3_BUGS: List[Dict[str, Any]] = [
    {
        "bug_id": "BUG-301",
        "title": "API rate limit returns 429 too aggressively",
        "description": "Users report hitting rate limits immediately. Rate limit is set to 100 req/min but users are hitting it at ~20 requests. Window seems to reset incorrectly.",
        "stack_trace": "RateLimitExceeded: 100 requests per 60 seconds\n  Counter value: 23 (should allow 77 more)",
        "steps_to_reproduce": "1. Make 20 API requests rapidly\n2. 21st request returns 429\n3. Wait 60 sec - counter resets to 0 but shouldn't",
        "reported_by": "developer@partner.com",
        "reporter_type": "customer",
        "created_at": "2024-01-17T08:00:00",
        "affected_version": "2.4.1",
        "environment": "production",
        "num_affected_users": 890,
        "has_workaround": False,
        "true_severity": "high",
        "true_component": "api",
        "reproduce_keywords": ["rate", "limit", "window", "counter", "redis", "sliding", "test"],
        "root_cause": "Fixed window counter instead of sliding window - resets at minute boundary, not 60s from first request",
        "diagnosis_keywords": ["fixed", "sliding", "window", "counter", "reset", "minute", "boundary"],
        "patch_keywords": ["sliding", "window", "redis", "sorted set", "zrangebyscore", "time"],
        "patch_valid_if": ["sliding", "window", "zrange", "sorted"],
        "test_valid_if": ["sliding", "window", "rate", "assert", "pass"],
        "is_duplicate_of": None,
        "is_by_design": False,
        "requires_escalation": False,
    },
    {
        "bug_id": "BUG-302",
        "title": "Getting 429 errors from API - broken?",
        "description": "Same as what others are reporting. API 429s after ~20 calls. This is unacceptable, we're paying customers.",
        "stack_trace": "HTTP 429 Too Many Requests",
        "steps_to_reproduce": "Make 25 API calls in 60 seconds",
        "reported_by": "angry@customer2.com",
        "reporter_type": "customer",
        "created_at": "2024-01-17T08:45:00",
        "affected_version": "2.4.1",
        "environment": "production",
        "num_affected_users": 890,
        "has_workaround": False,
        "true_severity": "high",
        "true_component": "api",
        "reproduce_keywords": [],
        "root_cause": "Duplicate of BUG-301",
        "diagnosis_keywords": ["duplicate", "BUG-301", "same", "rate", "limit"],
        "patch_keywords": [],
        "patch_valid_if": [],
        "test_valid_if": [],
        "is_duplicate_of": "BUG-301",
        "is_by_design": False,
        "requires_escalation": False,
    },
    {
        "bug_id": "BUG-303",
        "title": "Dark mode toggle resets on page refresh",
        "description": "User's dark mode preference isn't saved between sessions. Every refresh goes back to light mode.",
        "stack_trace": None,
        "steps_to_reproduce": "1. Enable dark mode\n2. Refresh page\n3. Back to light mode",
        "reported_by": "user@example.com",
        "reporter_type": "customer",
        "created_at": "2024-01-17T09:00:00",
        "affected_version": "2.4.0",
        "environment": "production",
        "num_affected_users": 4200,
        "has_workaround": False,
        "true_severity": "medium",
        "true_component": "frontend",
        "reproduce_keywords": ["localstorage", "preference", "persist", "dark", "mode", "cookie"],
        "root_cause": "Theme preference stored in memory only, not localStorage or cookie",
        "diagnosis_keywords": ["localstorage", "persist", "storage", "cookie", "preference", "session"],
        "patch_keywords": ["localStorage", "setItem", "getItem", "persist", "cookie", "preference"],
        "patch_valid_if": ["localStorage", "persist", "cookie", "storage"],
        "test_valid_if": ["localStorage", "persist", "refresh", "assert", "pass"],
        "is_duplicate_of": None,
        "is_by_design": False,
        "requires_escalation": False,
    },
    {
        "bug_id": "BUG-304",
        "title": "Free tier users can access premium features via direct URL",
        "description": "Free tier users who know the direct URL /premium/analytics can access premium analytics without paying. No server-side permission check - only UI gate.",
        "stack_trace": "No error - request succeeds with 200",
        "steps_to_reproduce": "1. Use free tier account\n2. Navigate directly to /premium/analytics\n3. Full premium data loads",
        "reported_by": "security@company.com",
        "reporter_type": "internal",
        "created_at": "2024-01-17T10:00:00",
        "affected_version": "2.4.0",
        "environment": "production",
        "num_affected_users": 0,
        "has_workaround": False,
        "true_severity": "critical",
        "true_component": "auth",
        "reproduce_keywords": ["permission", "auth", "check", "server", "middleware", "test"],
        "root_cause": "Authorization check only in frontend router, not in API endpoint - security through obscurity",
        "diagnosis_keywords": ["server-side", "middleware", "permission", "decorator", "check", "api", "frontend"],
        "patch_keywords": ["permission_required", "middleware", "decorator", "check", "server", "api", "tier"],
        "patch_valid_if": ["permission", "middleware", "decorator", "server", "check"],
        "test_valid_if": ["permission", "free", "tier", "assert", "403", "pass"],
        "is_duplicate_of": None,
        "is_by_design": False,
        "requires_escalation": True,
    },
    {
        "bug_id": "BUG-305",
        "title": "Search returns no results for accented characters",
        "description": "Searching for 'caf  ' returns 0 results but 'cafe' returns correct results. Affects users in French, Spanish, Portuguese markets.",
        "stack_trace": None,
        "steps_to_reproduce": "1. Create item named 'caf  '\n2. Search for 'caf  '\n3. 0 results returned",
        "reported_by": "i18n@company.com",
        "reporter_type": "internal",
        "created_at": "2024-01-17T11:00:00",
        "affected_version": "2.3.0",
        "environment": "production",
        "num_affected_users": 6700,
        "has_workaround": True,
        "true_severity": "medium",
        "true_component": "database",
        "reproduce_keywords": ["unicode", "collation", "normalize", "accent", "search", "test"],
        "root_cause": "Database collation is case-sensitive without Unicode normalization - '  ' != 'e'",
        "diagnosis_keywords": ["collation", "unicode", "normalize", "nfc", "nfd", "accent", "encoding"],
        "patch_keywords": ["normalize", "collation", "unicode", "NFC", "unaccent", "ilike", "extension"],
        "patch_valid_if": ["normalize", "unaccent", "collation", "unicode"],
        "test_valid_if": ["accent", "unicode", "assert", "results", "caf  ", "pass"],
        "is_duplicate_of": None,
        "is_by_design": False,
        "requires_escalation": False,
    },
    {
        "bug_id": "BUG-306",
        "title": "API returns all user data including deleted accounts",
        "description": "GET /api/admin/users returns deleted accounts in the list. These should be soft-deleted and excluded. GDPR concern - deleted user data should not be returned.",
        "stack_trace": None,
        "steps_to_reproduce": "1. Delete a user account\n2. GET /api/admin/users\n3. Deleted user appears in results",
        "reported_by": "legal@company.com",
        "reporter_type": "internal",
        "created_at": "2024-01-17T12:00:00",
        "affected_version": "2.4.1",
        "environment": "production",
        "num_affected_users": 0,
        "has_workaround": False,
        "true_severity": "critical",
        "true_component": "api",
        "reproduce_keywords": ["soft", "delete", "filter", "gdpr", "exclude", "test"],
        "root_cause": "QuerySet missing .filter(deleted_at__isnull=True) - soft delete pattern not applied to admin endpoint",
        "diagnosis_keywords": ["soft", "delete", "filter", "gdpr", "queryset", "deleted_at", "null"],
        "patch_keywords": ["deleted_at", "filter", "isnull", "soft", "exclude", "queryset"],
        "patch_valid_if": ["deleted_at", "filter", "isnull", "soft"],
        "test_valid_if": ["deleted", "assert", "not in", "exclude", "filter", "pass"],
        "is_duplicate_of": None,
        "is_by_design": False,
        "requires_escalation": True,
    },
    {
        "bug_id": "BUG-307",
        "title": "Pagination shows 'Page 1 of 0' when results exist",
        "description": "When search returns exactly 10 results (matching page size), pagination shows 'Page 1 of 0 pages'. Results are correct, just pagination math is wrong.",
        "stack_trace": None,
        "steps_to_reproduce": "1. Create exactly 10 items\n2. Search -> all 10 shown\n3. Footer shows 'Page 1 of 0'",
        "reported_by": "qa@company.com",
        "reporter_type": "internal",
        "created_at": "2024-01-17T13:00:00",
        "affected_version": "2.4.0",
        "environment": "staging",
        "num_affected_users": 0,
        "has_workaround": True,
        "true_severity": "low",
        "true_component": "frontend",
        "reproduce_keywords": ["pagination", "ceil", "math", "page", "count", "test"],
        "root_cause": "Integer division used: 10 // 10 = 1 then -1 applied -> 0. Should use math.ceil",
        "diagnosis_keywords": ["ceil", "division", "floor", "math", "integer", "pagination", "off by one"],
        "patch_keywords": ["ceil", "math.ceil", "ceiling", "round", "page", "count"],
        "patch_valid_if": ["ceil", "math.ceil", "ceiling"],
        "test_valid_if": ["page", "assert", "ceil", "10", "pass", "1"],
        "is_duplicate_of": None,
        "is_by_design": False,
        "requires_escalation": False,
    },
]

TASK3_CONFIG = {
    "task_id": "task3_hard_mixed_backlog",
    "description": (
        "Mixed backlog: 7 bugs including 1 duplicate, 2 security issues needing escalation, "
        "and a full debug cycle. Agent must spot patterns, avoid unnecessary work on duplicates, "
        "and correctly identify escalation-worthy security bugs."
    ),
    "difficulty": "hard",
    "max_steps": 45,
    "bugs": TASK3_BUGS,
    "required_actions": ["reproduce", "diagnose", "patch", "validate", "close"],
    "scoring": {
        "severity_weight": 0.15,
        "component_weight": 0.10,
        "reproduce_weight": 0.10,
        "diagnosis_weight": 0.25,
        "patch_weight": 0.20,
        "validation_weight": 0.10,
        "duplicate_detection_weight": 0.05,
        "escalation_accuracy_weight": 0.05,
    },
}

ALL_TASKS = {
    "task1_easy_severity_routing": TASK1_CONFIG,
    "task2_medium_full_debug_cycle": TASK2_CONFIG,
    "task3_hard_mixed_backlog": TASK3_CONFIG,
}
